### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by nipafx** [StreamOfJava/streamofjava.github.io#3]
The issue to end all issues. :grin: Let's talk about our website. Here are my thoughts...

# Requirements

Functional:

* schedule with all upcoming streams - front and center
* always (reasonably) up to date re what months are shown (e.g. current + upcoming)
* streamer profiles with bio, social media, etc. (?)

Technical:

* manual data entry (e.g. JSON) is ok, manual styling (like in a WordPress site) isn't
* site should be updated after every data entry

# Proposal

* data stored as JSON in GitHub repo
* static site (likely in same repo) builds from that
* built with GitHub Actions on each commit to `master` (possibly also nightly to show current/upcoming month)
* hosted with GitHub Pages

If we agree, we can start looking at the site's styling and tech choice for implementation. As an orientation, I create this schedule with Gatsby from JSON (still offline as of now):

![schedule](https://user-images.githubusercontent.com/6537432/93328092-8d7ff480-f81b-11ea-929d-f64df0cecf48.png)

**Comment by aymanapatel** [comment]
Any update on the website?

**Comment by nipafx** [comment]
Nope. This project is asleep right now, but I plan to get back to it in the coming months, say April or May.

**Comment by nipafx** [comment]
There we go: https://streamofjava.tv // cc @aymanapatel
